[package]
name = "etl_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.54", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.24.0"
rayon = "1.11"
